version: "3.8"
services:
    master: &conf
      container_name: master01
      image: mysql:5.7
      volumes:
        - master_data:/var/lib/mysql
      configs:
        - source: master_config
          target: /etc/mysql/conf.d/my.cnf

      environment:
        -  TZ=Asia/Shanghai
        -  MYSQL_ROOT_PASSWORD=123456
      networks:
        - mysql 
      ports:
        - "13306:3306"
    
    slave1:
      <<: *conf
      container_name: slave1
      volumes:
        - slave1_data:/var/lib/mysql
      configs:
        - source: slave1_config
          target: /etc/mysql/conf.d/my.cnf
      ports:
       - "13307:3306"
       


networks:
    mysql:


volumes:
   master_data:
   slave1_data:
   slave2_data:

configs:
   master_config:
     file: ./master/my.cnf
   slave1_config:
     file: ./slave1/my.cnf
   slave2_config:
     file: ./slave2/my.cnf
